import moment from 'moment'

export const message_api = [
    {
        id: 2,
        head_Text_url: 'Why-Given-Thanks-Is-Importance-Apostle-Jerry-Sanni',
        name: 'APOSTLE JERRY SANNI',
        title: 'WHY GIVEN THANKS IS IMPORTANCE ',
        description: `Given Thanks is  Necessary because of his Convernet keeping  and his goodness and mercy, his faithfullness and steadfastigness`,
        date:  moment('2023-01-01T07:30:00.000Z').format('LLLL'),
        eye_seen: '97.9k',
        social_on_image: `https://firebasestorage.googleapis.com/v0/b/nextplatform77-79102.appspot.com/o/nextplatform_img_2%2FapostleJerrySanni_why_thanks_is_importance.png?alt=media&token=62b0ac71-c49e-4907-af2c-15b5dc5a5349`,
        about_Main: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officia amet commodo enim ex aliqua irure ex ea veniam sunt laboris labore officia. Velit adipisicing pariatur reprehenderit duis pariatur ex duis culpa voluptate. Est tempor amet esse id veniam elit exercitation excepteur incididunt consectetur ea culpa duis irure. Aliquip eiusmod aute veniam incididunt. Dolor consectetur eiusmod ipsum tempor pariatur ad.loremUllamco elit ullamco veniam sit ullamco. Consequat sint consectetur incididunt dolore mollit nisi proident amet aliqua do quis irure. Esse exercitation adipisicing proident mollit. Non est duis aliqua anim sunt in voluptate do labore Lorem. Fugiat id ex excepteur dolor dolor cillum ea aliquip est quis duis.loremAliquip ex veniam in eiusmod nisi eiusmod ex nisi dolor labore. Magna ut duis aliquip elit irure anim laboris est nostrud duis. Velit nisi voluptate commodo culpa eu consectetur anim nostrud irure ex exercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400Laborum incididunt nisi mollit ea commodo. Proident veniam voluptate officia quis ipsum sit eu in do et veniam laboris. Irure proident quis est qui .
        loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officia amet commodo enim ex aliqua irure ex ea veniam sunt laboris labore officia. Velit adipisicing pariatur reprehenderit duis pariatur ex duis culpa voluptate. Est tempor amet esse id veniam elit exercitation excepteur incididunt consectetur ea culpa duis irure. Aliquip eiusmod aute veniam incididunt. Dolor consectetur eiusmod ipsum tempor pariatur ad.loremUllamco elit ullamco veniam sit ullamco. Consequat sint consectetur incididunt dolore mollit nisi proident amet aliqua do quis irure. Esse exercitation adipisicing proident mollit. Non est duis aliqua anim sunt in voluptate do labore Lorem. Fugiat id ex excepteur dolor dolor cillum ea aliquip est quis duis.loremAliquip ex veniam in eiusmod nisi eiusmod ex nisi dolor labore. Magna ut duis aliquip elit irure anim laboris est nostrud duis. Velit nisi voluptate commodo culpa eu consectetur anim nostrud irure ex exercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400Laborum incididunt nisi mollit ea commodo. Proident veniam voluptate officia quis ipsum sit eu in do et veniam laboris. Irure proident quis est qui. `,
        about_Main_2: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt.exercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
        about_Main_3: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officiaexercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
        about_Main_4: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officiaexercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
        about_Main_5: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officiaexercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
    },
    {
        id: 1,
        head_Text_url: 'Fruit-of-the-Holy-Spirit-Apostle-Jerry-Sanni',
        name: 'APOSTLE JERRY SANNI',
        title: 'FRUIT OF THE SPIRIT ',
        description: `The fruit of the Spirit is love, joy, peace, patience, kindness, generosity, faithfulness, gentleness, self-control…” Those who are in Christ are distinguished from unbelievers in that they have been gifted with the Holy Spirit, enabling them to bear fruit.`,
        date:  moment('2022-05-03T14:48:00.000Z').format('LLLL'),
        eye_seen: '87.9k',
        social_on_image: `https://firebasestorage.googleapis.com/v0/b/nextplatform77-79102.appspot.com/o/nextplatform_img_2%2FApostleJerrySanni_Fruit_of_the_spirit.jpg?alt=media&token=690cf1f8-ed90-4b01-896a-efd7aab34419`,
        about_Main: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officia amet commodo enim ex aliqua irure ex ea veniam sunt laboris labore officia. Velit adipisicing pariatur reprehenderit duis pariatur ex duis culpa voluptate. Est tempor amet esse id veniam elit exercitation excepteur incididunt consectetur ea culpa duis irure. Aliquip eiusmod aute veniam incididunt. Dolor consectetur eiusmod ipsum tempor pariatur ad.loremUllamco elit ullamco veniam sit ullamco. Consequat sint consectetur incididunt dolore mollit nisi proident amet aliqua do quis irure. Esse exercitation adipisicing proident mollit. Non est duis aliqua anim sunt in voluptate do labore Lorem. Fugiat id ex excepteur dolor dolor cillum ea aliquip est quis duis.loremAliquip ex veniam in eiusmod nisi eiusmod ex nisi dolor labore. Magna ut duis aliquip elit irure anim laboris est nostrud duis. Velit nisi voluptate commodo culpa eu consectetur anim nostrud irure ex exercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400Laborum incididunt nisi mollit ea commodo. Proident veniam voluptate officia quis ipsum sit eu in do et veniam laboris. Irure proident quis est qui .
        loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officia amet commodo enim ex aliqua irure ex ea veniam sunt laboris labore officia. Velit adipisicing pariatur reprehenderit duis pariatur ex duis culpa voluptate. Est tempor amet esse id veniam elit exercitation excepteur incididunt consectetur ea culpa duis irure. Aliquip eiusmod aute veniam incididunt. Dolor consectetur eiusmod ipsum tempor pariatur ad.loremUllamco elit ullamco veniam sit ullamco. Consequat sint consectetur incididunt dolore mollit nisi proident amet aliqua do quis irure. Esse exercitation adipisicing proident mollit. Non est duis aliqua anim sunt in voluptate do labore Lorem. Fugiat id ex excepteur dolor dolor cillum ea aliquip est quis duis.loremAliquip ex veniam in eiusmod nisi eiusmod ex nisi dolor labore. Magna ut duis aliquip elit irure anim laboris est nostrud duis. Velit nisi voluptate commodo culpa eu consectetur anim nostrud irure ex exercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400Laborum incididunt nisi mollit ea commodo. Proident veniam voluptate officia quis ipsum sit eu in do et veniam laboris. Irure proident quis est qui. `,
        about_Main_2: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt.exercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
        about_Main_3: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officiaexercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
        about_Main_4: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officiaexercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
        about_Main_5: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officiaexercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
    },
  
    {
        id: 4,
        head_Text_url: 'Belivers-Resoucess-In-This-Last-Days-Apostle-Jerry-Sanni',
        name: 'APOSTLE JERRY SANNI',
        title: 'BELIVERS RESOUCESS IN THIS LAST DAYS',
        description: `Faith,The Spirit of God, The Word of God, The Grace Of Christ is Belivers Resoucess In This Last Days`,
        date:  moment('2022-11-03T14:48:00.000Z').format('LLLL'),
        eye_seen: '65.9k',
        social_on_image: 'https://firebasestorage.googleapis.com/v0/b/nextplatform77-79102.appspot.com/o/nextplatform_img_2%2FBelivers-Resoucess-In-This-Last-Days-Apostle-Jerry-Sanni.png?alt=media&token=a158b1d6-0635-4cbc-8f34-8616c3c0406e',
        about_Main: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officia amet commodo enim ex aliqua irure ex ea veniam sunt laboris labore officia. Velit adipisicing pariatur reprehenderit duis pariatur ex duis culpa voluptate. Est tempor amet esse id veniam elit exercitation excepteur incididunt consectetur ea culpa duis irure. Aliquip eiusmod aute veniam incididunt. Dolor consectetur eiusmod ipsum tempor pariatur ad.loremUllamco elit ullamco veniam sit ullamco. Consequat sint consectetur incididunt dolore mollit nisi proident amet aliqua do quis irure. Esse exercitation adipisicing proident mollit. Non est duis aliqua anim sunt in voluptate do labore Lorem. Fugiat id ex excepteur dolor dolor cillum ea aliquip est quis duis.loremAliquip ex veniam in eiusmod nisi eiusmod ex nisi dolor labore. Magna ut duis aliquip elit irure anim laboris est nostrud duis. Velit nisi voluptate commodo culpa eu consectetur anim nostrud irure ex exercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400Laborum incididunt nisi mollit ea commodo. Proident veniam voluptate officia quis ipsum sit eu in do et veniam laboris. Irure proident quis est qui .
        loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officia amet commodo enim ex aliqua irure ex ea veniam sunt laboris labore officia. Velit adipisicing pariatur reprehenderit duis pariatur ex duis culpa voluptate. Est tempor amet esse id veniam elit exercitation excepteur incididunt consectetur ea culpa duis irure. Aliquip eiusmod aute veniam incididunt. Dolor consectetur eiusmod ipsum tempor pariatur ad.loremUllamco elit ullamco veniam sit ullamco. Consequat sint consectetur incididunt dolore mollit nisi proident amet aliqua do quis irure. Esse exercitation adipisicing proident mollit. Non est duis aliqua anim sunt in voluptate do labore Lorem. Fugiat id ex excepteur dolor dolor cillum ea aliquip est quis duis.loremAliquip ex veniam in eiusmod nisi eiusmod ex nisi dolor labore. Magna ut duis aliquip elit irure anim laboris est nostrud duis. Velit nisi voluptate commodo culpa eu consectetur anim nostrud irure ex exercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400Laborum incididunt nisi mollit ea commodo. Proident veniam voluptate officia quis ipsum sit eu in do et veniam laboris. Irure proident quis est qui.`,
        about_Main_2: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt.exercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
        about_Main_3: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officiaexercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
        about_Main_4: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officiaexercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
        about_Main_5: `loremAd officia dolor nisi dolor deserunt anim. Consequat sunt enim pariatur deserunt sunt. Officiaexercitation eiusmod nisi. Elit aliqua occaecat qui duis velit ut. Nulla commodo fugiat culpa enim id ipsum nisi anim nisi excepteur duis.lorem400L. `,
    },
   
 
    
 

]